### ISSUE TITLE
Forcing the user to confirm the mobile before logging in and using the site

### ISSUE THREAD

**Issue by saeed7m** [mohammad-fouladgar/laravel-mobile-verification#27]
Thanks for the great package!
Do you have a sample code for VIEW  and Routing that guides in such a way that the user is directed to the page immediately after registration to enter the code sent to his mobile phone, and if it is not correct, he is prevented from accessing his profile pages  and maybe requests code again?

thank you .

**Comment by mohammad-fouladgar** [comment]
@saeed7m So thanks.
After user registration, a code will be sent to the user through SMS.
The user must login via anyway in the system, as "**[verify](https://github.com/mohammad-fouladgar/laravel-mobile-verification#verify)**" and "**[re-send](https://github.com/mohammad-fouladgar/laravel-mobile-verification#resend)**" actions need to have a user authenticated. 
If you would like to protected some routes you can use the "**[mobile.verifie](https://github.com/mohammad-fouladgar/laravel-mobile-verification#protecting-routes)**" middleware.
With this middleware, you only allow verified users to access a given route.

**Comment by mohammad-fouladgar** [comment]
@saeed7m 
Now, if you're not using AJAX requests, you'll need to create some form to call "verify" and "re-send" routes.
Of course, only a logged-in user should have access to these forms.

**Comment by mohammad-fouladgar** [comment]
After user registration, a code will be sent to the user via SMS.
Then user must login to system, because "**[verify](https://github.com/mohammad-fouladgar/laravel-mobile-verification#verify)**" and "**[re-send](https://github.com/mohammad-fouladgar/laravel-mobile-verification#resend)**" actions need authenticated user.If you like to protect your routes, you can use the "**[mobile.verified](https://github.com/mohammad-fouladgar/laravel-mobile-verification#protecting-routes)**" middleware. This middleware, only allows verified users to access a given route.Now, if you're not using AJAX requests, you'll need to create some form to call "verify" and "re-send" routes and obviously only a logged-in user should have access to these forms

**Comment by saeed7m** [comment]
thanks man.

**Comment by thedanmwangi** [comment]
Have encountered an issue related to this.

I am using both Laravel Socialite and Laravel Fortify to authenticate my users.

Registration in Laravel Fortify has integrated perfectly with this Package, but Login has (if I can call it) a loop hole.
When I attempt to Login a user whose Mobile is not Verified, the browser returns a "too many redirects" error.

The same case happens to Laravel Socialite. Socialite does not provide the system with a user's mobile number, I have to fetch it directly from the user using a form. Adding a form that fetches this info and sending it to the route "mobile.verify" does not do anything. It directs to Home and then returns the 'too many redirects" error.

Perhaps:
1. If the package could have a fall back route for when a user is not verified it would fix the too many redirects issue.
2. If the package could point out a dedicated view for which users can manually enter their mobile numbers and send it to a specific controller, one that Validates then triggers the event(new Registered($user)); Event, it would work for even users logged in via Laravel Socialite.

Kindly, let me know your thoughts.
